name: Pull request size and stability labels
description: This action marks PRs with size and estimated stability labels
author: victorx64
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ github.action_path }}/devrating.sqlite3
        key: devrating.sqlite3-${{ github.run_id }}
        restore-keys: |
          devrating.sqlite3-

    # on pull_request
    - uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        dotnet run --project ${{ github.action_path }}/on-pull_request/on-pull_request.csproj -- `
        '${{ github.repository }}' `
        '${{ github.token }}' `
        '${{ github.workspace }}' `
        '${{ github.base_ref }}' `
        '${{ github.event.pull_request.number }}' `
        '${{ github.event.pull_request.base.sha }}' `
        '${{ github.event.pull_request.head.sha }}' `
        '${{ github.action_path }}/devrating.sqlite3'
      if: github.event_name == 'pull_request'
      shell: pwsh
    - run: rm '${{ github.action_path }}/devrating.sqlite3'
      if: github.event_name == 'pull_request'
      shell: pwsh

    # on push
    - uses: actions/checkout@v3
      if: github.event_name == 'push'
      with:
        fetch-depth: 0
    - run: |
        dotnet run --project ${{ github.action_path }}/on-push/on-push.csproj -- `
        '${{ github.repository }}' `
        '${{ github.token }}' `
        '${{ github.workspace }}' `
        '${{ github.ref_name }}' `
        '${{ github.action_path }}/devrating.sqlite3'
      if: github.event_name == 'push'
      shell: pwsh
    - uses: actions/upload-artifact@v3
      if: github.event_name == 'push'
      with:
        name: devrating.sqlite3
        path: ${{ github.action_path }}/devrating.sqlite3
branding:
  icon: git-pull-request
  color: blue
